/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagement;

import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.MessageFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author royce
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    
    private static final String username= "root";
     private static final String password= "root";
      private static final String url= "jdbc:mysql://localhost:3306/school";
    
    Connection sqlCon = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int q,i,id,delete;
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void upData() throws ClassNotFoundException{
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            sqlCon = DriverManager.getConnection(url,username,password);
            pst = sqlCon.prepareStatement("select * from school");
            rs = pst.executeQuery();
            ResultSetMetaData stdata = rs.getMetaData();
            
            q = stdata.getColumnCount();
            DefaultTableModel recordtable = (DefaultTableModel)jTable1.getModel();
            recordtable.setRowCount(0);
            
            while (rs.next()){
                Vector columnData = new Vector();
                for(i=1;i<=q;i++){
                    columnData.add(rs.getString("ID"));
                    columnData.add(rs.getString("StudentID"));
                    columnData.add(rs.getString("Firstname"));
                    columnData.add(rs.getString("Surname"));
                    columnData.add(rs.getString("Address"));
                    columnData.add(rs.getString("Gender"));
                    columnData.add(rs.getString("DOB"));
                    columnData.add(rs.getString("Phone"));
                    columnData.add(rs.getString("Email"));
                    columnData.add(rs.getString("Guidance"));
                    columnData.add(rs.getString("GFirstname"));
                    columnData.add(rs.getString("GSurname"));
                    columnData.add(rs.getString("GAddress"));
                    
                    columnData.add(rs.getString("GPhone"));
                    columnData.add(rs.getString("GEmail"));
                    columnData.add(rs.getString("Course Code"));
                }
                recordtable.addRow(columnData);
            }
            
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jcbocourse = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbobscsci = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbobscmaths = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbobsccs = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcvobscit = new javax.swing.JComboBox<>();
        jcbogui = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbo3 = new javax.swing.JComboBox<>();
        jcbo2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbo1 = new javax.swing.JComboBox<>();
        jcbo5 = new javax.swing.JComboBox<>();
        jtxtgemail = new javax.swing.JTextField();
        jtxtgfn = new javax.swing.JTextField();
        jtxtgsn = new javax.swing.JTextField();
        jtxtgadd = new javax.swing.JTextField();
        jtxtgphone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtxtemail = new javax.swing.JTextField();
        jtxtphone = new javax.swing.JTextField();
        jtxtsn = new javax.swing.JTextField();
        jtxtfn = new javax.swing.JTextField();
        jtxtstdid = new javax.swing.JTextField();
        jcbogen = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jtxttutor = new javax.swing.JTextField();
        jtxtleader = new javax.swing.JTextField();
        jtxtdean = new javax.swing.JTextField();
        jtxtfaculty = new javax.swing.JTextField();
        jtxtCoursecode = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jcbo4 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jbtnexit = new javax.swing.JButton();
        jbtnaddnew = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jtxtadd1 = new javax.swing.JTextField();
        jtxtdob = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jcvobscit1 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jcvobscit2 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jcvobscit3 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbocourse.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbocourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Course", "Bsc Science", "Bsc Maths", "Bsc Cs", "Bsc IT" }));
        jPanel3.add(jcbocourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 140, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Course:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("IFS");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, -1, -1));

        jcbobscsci.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbobscsci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcbobscsci, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("END");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, -1, -1));

        jcbobscmaths.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbobscmaths.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcbobscmaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("AI");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, -1, -1));

        jcbobsccs.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbobsccs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcbobsccs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 140, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("OR");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, -1, -1));

        jcvobscit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcvobscit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcvobscit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 140, -1));

        jcbogui.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbogui.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mother", "Father", "Brother", "Sister", "Guardian" }));
        jPanel3.add(jcbogui, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Scholarship");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Accomadation");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        jcbo3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcbo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 140, -1));

        jcbo2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcbo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 140, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Oversea Student");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Email:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jcbo1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcbo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 140, -1));

        jcbo5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcbo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 140, -1));
        jPanel3.add(jtxtgemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 140, -1));
        jPanel3.add(jtxtgfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 140, -1));
        jPanel3.add(jtxtgsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 140, -1));
        jPanel3.add(jtxtgadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 140, -1));
        jPanel3.add(jtxtgphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 140, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Rochelle D'lima");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 620, 160, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Guidance:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Firstname:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Surname:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Address:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Phone:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Student ID:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Firstname:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Surname:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Phone:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Email:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));
        jPanel3.add(jtxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 140, -1));
        jPanel3.add(jtxtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 140, -1));
        jPanel3.add(jtxtsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 140, -1));
        jPanel3.add(jtxtfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, -1));
        jPanel3.add(jtxtstdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 140, -1));

        jcbogen.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbogen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other" }));
        jPanel3.add(jcbogen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 140, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Course code:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Faculty Name:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Dean:");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Program Leader:");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Course Tutor:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));
        jPanel3.add(jtxttutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 140, -1));
        jPanel3.add(jtxtleader, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 140, -1));

        jtxtdean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdeanActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtdean, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 140, -1));
        jPanel3.add(jtxtfaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 140, -1));
        jPanel3.add(jtxtCoursecode, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 140, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Address:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jcbo4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcbo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcbo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 140, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Exchange");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        jbtnexit.setText("Exit");
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 130, 40));

        jbtnaddnew.setText("Add New");
        jbtnaddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddnewActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnaddnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 130, 40));

        jbtnreset.setText("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 130, 40));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Gender:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("DOB:");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        jPanel3.add(jtxtadd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, -1));
        jPanel3.add(jtxtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 140, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText("MIS");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, -1, -1));

        jcvobscit1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcvobscit1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcvobscit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 140, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setText("MOAD");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, -1, -1));

        jcvobscit2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcvobscit2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcvobscit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 140, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel36.setText("AADL");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, -1, -1));

        jcvobscit3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jcvobscit3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "NO", "YES" }));
        jPanel3.add(jcvobscit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, 140, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setText("Home Student");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 670));

        jTabbedPane1.addTab("school sys", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("School Management System");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 340, 90));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "43", "Rochelle", "D'lima", "Anand Park", "9930472349", "rochelledlima@gmail.com", "Female", "04/02/1999", "Sister", "Jovita", "D'lima", "9930472349", "jovidlima@gmail.com", "Anand Park", "420"},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Student Id", "First Name", "Surname", "Address", "Phone", "Email", "Gender", "DOB", "Guidance", "G.First name", "G.Last name", "G. Phone", "G. email", "G. address", "Course code"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 21, 1310, 480));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1350, 530));

        jTabbedPane1.addTab("student details", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1380, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtdeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdeanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdeanActionPerformed
private JFrame frame;
    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","School management",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        // TODO add your handling code here:
        JTextField jtxt= null;
        JComboBox jcbogen = null;
        JComboBox jcbogui = null;
        JComboBox jcbo1 = null;
        JComboBox jcbo2 = null;
        JComboBox jcbo3 = null;
        JComboBox jcbo4 = null;
        JComboBox jcbo5 = null;
        JComboBox jcbobscsc = null;
        JComboBox jcbobscmaths = null;
        JComboBox jcbobsccs = null;
        JComboBox jcbobscit = null;
        JComboBox jcbocourse = null;
        JTextField jtxtadd1= null;
        JTextField jtxtstdid= null;
        JTextField jtxtemail= null;
        JTextField jtxtphone= null;
        JTextField jtxtfn= null;
        JTextField jtxtsn= null;
        JTextField jtxtgfn= null;
        JTextField jtxtgsn= null;
        JTextField jtxtgphone= null;
        JTextField jtxtgadd= null;
        JTextField jtxtgemail= null;
        JTextField jtxtdob= null;
        JTextField jtxtCoursecode= null;
        for (Component c:jPanel3.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                jtxt=(JTextField) c;
                jtxt.setText(null);
            }
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                
            }
        }
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jbtnaddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddnewActionPerformed
        // TODO add your handling code here:
       // try{
            //Class.forName("com.mysql.jdbc.Driver");
            // sqlCon = DriverManager.getConnection(username,password,url);
            // pst = sqlCon.prepareStatement("insert into school (StudentID,Firstname,Surname,Address,Gender," + "DOB,Email,Phone,Guidance,GFirsstname,GSurname,GPhone,GEmail,GAddress,Course Code)"
                 //    + "value(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
           //  pst.setString(1,jtxtstdid.getText());
           //  pst.setString(2,jtxtfn.getText());
            // pst.setString(3,jtxtsn.getText());
            // pst.setString(4,jtxtphone.getText());
            // pst.setString(5,jtxtadd1.getText());
           //  pst.setString(6,(String)jcbogen.getSelectedItem());
          //   pst.setString(7,jtxtdob.getText());
          //   pst.setString(8,jtxtemail.getText());
         //    pst.setString(9,(String)jcbogui.getSelectedItem());
         //    pst.setString(10,jtxtgfn.getText());
         //    pst.setString(11,jtxtgsn.getText());
          //   pst.setString(12,jtxtgadd.getText());
         //    pst.setString(13,jtxtgphone.getText());
         //    pst.setString(14,jtxtgemail.getText());
            // pst.setString(15,jtxtCoursecode.getText());
             
          //   pst.executeUpdate();
             JOptionPane.showMessageDialog(this,"School record updated");
           //  upData();
           
       // }
       //catch (ClassNotFoundException | SQLException ex) {
       //     java.util.logging.Logger.getLogger(Schoolmanagement.class.getName()).log(java.util.logging.Level.SEVERE ,null,ex);
       // }
    }//GEN-LAST:event_jbtnaddnewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnaddnew;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JComboBox<String> jcbo1;
    private javax.swing.JComboBox<String> jcbo2;
    private javax.swing.JComboBox<String> jcbo3;
    private javax.swing.JComboBox<String> jcbo4;
    private javax.swing.JComboBox<String> jcbo5;
    private javax.swing.JComboBox<String> jcbobsccs;
    private javax.swing.JComboBox<String> jcbobscmaths;
    private javax.swing.JComboBox<String> jcbobscsci;
    private javax.swing.JComboBox<String> jcbocourse;
    private javax.swing.JComboBox<String> jcbogen;
    private javax.swing.JComboBox<String> jcbogui;
    private javax.swing.JComboBox<String> jcvobscit;
    private javax.swing.JComboBox<String> jcvobscit1;
    private javax.swing.JComboBox<String> jcvobscit2;
    private javax.swing.JComboBox<String> jcvobscit3;
    private javax.swing.JTextField jtxtCoursecode;
    private javax.swing.JTextField jtxtadd1;
    private javax.swing.JTextField jtxtdean;
    private javax.swing.JTextField jtxtdob;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtfaculty;
    private javax.swing.JTextField jtxtfn;
    private javax.swing.JTextField jtxtgadd;
    private javax.swing.JTextField jtxtgemail;
    private javax.swing.JTextField jtxtgfn;
    private javax.swing.JTextField jtxtgphone;
    private javax.swing.JTextField jtxtgsn;
    private javax.swing.JTextField jtxtleader;
    private javax.swing.JTextField jtxtphone;
    private javax.swing.JTextField jtxtsn;
    private javax.swing.JTextField jtxtstdid;
    private javax.swing.JTextField jtxttutor;
    // End of variables declaration//GEN-END:variables
}
